import { describe, expect, it } from "vitest";
import { JsonlDecoder } from "../src/core/jsonl";
import { array, fencedText, minimalEnvironment, record, redact, safeText } from "../src/core/privacy";
import { isTerminal, transition } from "../src/core/state-machine";
import { lifecycleEvents, taskStates } from "../src/core/types";
import { validateStart } from "../src/core/validation";
import { encodeClaudeCwd } from "../src/monitor/claude-path";
import { request } from "./helpers";

describe("task state machine", () => {
  it("never revives a terminal task, for every event", () => {
    for (const state of taskStates)
      for (const event of lifecycleEvents) {
        const next = transition(state, event);
        expect(taskStates).toContain(next);
        if (isTerminal(state)) expect(next).toBe(state);
      }
  });
  it("retains cancellation intent across racing completions", () => {
    expect(transition("starting", "started")).toBe("running");
    expect(transition("running", "stop")).toBe("stopping");
    for (const event of ["succeeded", "failed", "stopped", "lost"] as const)
      expect(transition("stopping", event)).toBe("cancelled");
    expect(transition("running", "lost")).toBe("interrupted");
    expect(transition("running", "timeout")).toBe("timed-out");
  });
});

describe("incremental JSONL", () => {
  it("handles every UTF-8 byte boundary, CRLF and a final unterminated record", () => {
    const values: unknown[] = [];
    let errors = 0;
    const parser = new JsonlDecoder(
      (v) => values.push(v),
      () => errors++,
    );
    for (const byte of Buffer.from('\r\n{"text":"你好"}\r\ninvalid\n{"done":true}')) parser.push(Buffer.from([byte]));
    parser.end();
    expect(values).toEqual([{ text: "你好" }, { done: true }]);
    expect(errors).toBe(1);
  });
  it("recovers after an oversized record and discards an oversized unterminated record", () => {
    const values: unknown[] = [];
    let errors = 0;
    const parser = new JsonlDecoder(
      (v) => values.push(v),
      () => errors++,
      12,
    );
    parser.push(Buffer.from("x".repeat(20)));
    parser.push(Buffer.from('x\n{"ok":1}\n'));
    parser.end();
    parser.push(Buffer.from("x".repeat(20)));
    parser.end();
    expect(values).toEqual([{ ok: 1 }]);
    expect(errors).toBe(2);
  });
});

describe("privacy boundaries", () => {
  it("removes common credential patterns and leaves ordinary text intact", () => {
    const secrets = [
      "sk-" + "x".repeat(24),
      "AKIA" + "A".repeat(16),
      "Bearer " + "abc".repeat(10),
      "ghp_" + "a".repeat(30),
      "password=not-a-real-password",
      "-----BEGIN PRIVATE KEY-----\ntest\n-----END PRIVATE KEY-----",
      "eyJaaa.eyJbbb.signature",
    ];
    for (const secret of secrets) expect(redact(secret)).toContain("[REDACTED]");
    expect(redact("normal task\u001b[31m output")).toBe("normal task output");
    expect(safeText(undefined, "fallback")).toBe("fallback");
    expect(safeText("a".repeat(5000))).toHaveLength(4000);
    expect(record(null)).toEqual({});
    expect(record({ ok: true })).toEqual({ ok: true });
    expect(array(null)).toEqual([]);
    expect(array([1])).toEqual([1]);
    expect(fencedText("![tracking](https://example.invalid)\n```escape")).toMatch(/^````/);
    expect(fencedText("normal")).toBe("```\nnormal\n```");
  });
  it("passes only explicit benign environment keys", () => {
    const env = minimalEnvironment({
      HOME: "/fake",
      PATH: "/bin",
      OPENAI_API_KEY: "private",
      ANTHROPIC_API_KEY: "private",
      NODE_OPTIONS: "--inspect",
      CCS_TEST_SECRET: "private",
    });
    expect(env.HOME).toBe("/fake");
    expect(env.PATH).toBe("/bin");
    expect(env.OPENAI_API_KEY).toBeUndefined();
    expect(env.NODE_OPTIONS).toBeUndefined();
    expect(env.CCS_TEST_SECRET).toBeUndefined();
    expect(env.DO_NOT_TRACK).toBe("1");
  });
});

describe("Claude CWD encoding", () => {
  it("matches observed SDK replacement semantics", () => {
    expect(encodeClaudeCwd("/Users/me/a.b_c d")).toBe("-Users-me-a-b-c-d");
    expect(encodeClaudeCwd("C:\\work\\中文")).toBe("C--work---");
    expect(encodeClaudeCwd("/🙂")).toBe("---");
    expect(encodeClaudeCwd("a".repeat(200))).toBe("a".repeat(200));
  });
  it("locks the original-path signed hash for >200 UTF-16 code units", () => {
    // Golden generated by executing the encoding functions from the published 0.2.114 SDK.
    expect(encodeClaudeCwd("a".repeat(201))).toBe("a".repeat(200) + "-rkvsv5");
    expect(encodeClaudeCwd("/" + "a".repeat(201))).not.toBe(encodeClaudeCwd("-" + "a".repeat(201)));
  });
});

describe("untrusted IPC request validation", () => {
  it("accepts explicit valid requests", () => expect(validateStart(request())).toEqual(request()));
  it.each([
    { engine: "remote" },
    { cwd: "relative" },
    { prompt: "" },
    { prompt: "x".repeat(64001) },
    { timeoutMs: 0 },
    { timeoutMs: Infinity },
    { persistSession: "yes" },
    { claudePermission: "invented" },
    { sandbox: "invented" },
    { codexApproval: "invented" },
    { allowedTools: [1] },
    { deniedTools: ["x\narg"] },
    { allowedTools: {} },
    { executable: "claude" },
    { resume: 1 },
    { resume: "--remote" },
  ])("rejects invalid input %j", (fields) => expect(() => validateStart({ ...request(), ...fields })).toThrow());
  it("validates resume IDs without interpreting flags", () =>
    expect(validateStart(request({ resume: "last" })).resume).toBe("last"));
});
